apiVersion: v1
kind: Service
metadata:
  name: rhythm-service
  namespace: default
spec:
  selector:
    app: rhythm-ms
  ports:
    - port: 2022
      targetPort: 2022
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rhythm-ms-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhythm-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rhythm-ms
    spec:
      containers:
      - name: myapp
        image: docker.io/anh3h/rhythm-ms
        imagePullPolicy: IfNotPresent
        env:
          - name: eureka.instance.hostname
            value: 35.185.8.176
          - name: ribbon.listOfServers
            value: 35.185.8.176:9090
          - name: eureka.client.serviceUrl.defaultZone
            value: http://35.185.8.176:8761/eureka
          - name: activemq.brokerUrl
            value: tcp:// 35.237.151.82:61616
          - name: cassandra.contactPoints
            value: 35.227.125.206:9042
          - name: mariadb.host
            value: 35.196.130.21
        ports:
          - containerPort: 2024
